"""Hardcoded team data for the 2026 FIFA World Cup."""

HOSTS = ["USA", "Mexico", "Canada"]

TEAMS = [
    {"name": "Argentina", "code": "ARG", "confederation": "CONMEBOL", "fifa_rank": 1, "rating": 1876.11, "pot": 1},
    {"name": "Spain", "code": "ESP", "confederation": "UEFA", "fifa_rank": 2, "rating": 1873.87, "pot": 1},
    {"name": "France", "code": "FRA", "confederation": "UEFA", "fifa_rank": 3, "rating": 1870.69, "pot": 1},
    {"name": "England", "code": "ENG", "confederation": "UEFA", "fifa_rank": 4, "rating": 1827.05, "pot": 1},
    {"name": "Portugal", "code": "POR", "confederation": "UEFA", "fifa_rank": 5, "rating": 1766.17, "pot": 1},
    {"name": "Brazil", "code": "BRA", "confederation": "CONMEBOL", "fifa_rank": 6, "rating": 1765.86, "pot": 1},
    {"name": "Morocco", "code": "MOR", "confederation": "CAF", "fifa_rank": 7, "rating": 1755.44, "pot": 2},
    {"name": "Netherlands", "code": "NED", "confederation": "UEFA", "fifa_rank": 8, "rating": 1753.57, "pot": 1},
    {"name": "Belgium", "code": "BEL", "confederation": "UEFA", "fifa_rank": 9, "rating": 1742.23, "pot": 1},
    {"name": "Germany", "code": "GER", "confederation": "UEFA", "fifa_rank": 10, "rating": 1735.77, "pot": 1},
    {"name": "Croatia", "code": "CRO", "confederation": "UEFA", "fifa_rank": 11, "rating": 1714.87, "pot": 2},
    {"name": "Colombia", "code": "COL", "confederation": "CONMEBOL", "fifa_rank": 13, "rating": 1698.35, "pot": 2},
    {"name": "Mexico", "code": "MEX", "confederation": "CONCACAF", "fifa_rank": 14, "rating": 1687.48, "pot": 1},
    {"name": "Senegal", "code": "SEN", "confederation": "CAF", "fifa_rank": 15, "rating": 1685.24, "pot": 2},
    {"name": "Uruguay", "code": "URU", "confederation": "CONMEBOL", "fifa_rank": 16, "rating": 1673.07, "pot": 2},
    {"name": "USA", "code": "USA", "confederation": "CONCACAF", "fifa_rank": 17, "rating": 1671.24, "pot": 1},
    {"name": "Japan", "code": "JPN", "confederation": "AFC", "fifa_rank": 18, "rating": 1661.58, "pot": 2},
    {"name": "Switzerland", "code": "SUI", "confederation": "UEFA", "fifa_rank": 19, "rating": 1650.07, "pot": 2},
    {"name": "Iran", "code": "IRN", "confederation": "AFC", "fifa_rank": 21, "rating": 1619.58, "pot": 2},
    {"name": "Turkey", "code": "TUR", "confederation": "UEFA", "fifa_rank": 22, "rating": 1605.73, "pot": 4},
    {"name": "Ecuador", "code": "ECU", "confederation": "CONMEBOL", "fifa_rank": 23, "rating": 1598.51, "pot": 2},
    {"name": "Austria", "code": "AUT", "confederation": "UEFA", "fifa_rank": 24, "rating": 1597.41, "pot": 2},
    {"name": "South Korea", "code": "KOR", "confederation": "AFC", "fifa_rank": 25, "rating": 1591.63, "pot": 2},
    {"name": "Australia", "code": "AUS", "confederation": "AFC", "fifa_rank": 27, "rating": 1579.34, "pot": 2},
    {"name": "Algeria", "code": "ALG", "confederation": "CAF", "fifa_rank": 28, "rating": 1571.04, "pot": 3},
    {"name": "Egypt", "code": "EGY", "confederation": "CAF", "fifa_rank": 29, "rating": 1562.37, "pot": 3},
    {"name": "Canada", "code": "CAN", "confederation": "CONCACAF", "fifa_rank": 30, "rating": 1559.48, "pot": 1},
    {"name": "Norway", "code": "NOR", "confederation": "UEFA", "fifa_rank": 31, "rating": 1557.44, "pot": 3},
    {"name": "Ivory Coast", "code": "CIV", "confederation": "CAF", "fifa_rank": 33, "rating": 1540.87, "pot": 3},
    {"name": "Panama", "code": "PAN", "confederation": "CONCACAF", "fifa_rank": 34, "rating": 1539.15, "pot": 3},
    {"name": "Sweden", "code": "SWE", "confederation": "UEFA", "fifa_rank": 38, "rating": 1509.79, "pot": 4},
    {"name": "Czechia", "code": "CZE", "confederation": "UEFA", "fifa_rank": 39, "rating": 1505.74, "pot": 4},
    {"name": "Paraguay", "code": "PAR", "confederation": "CONMEBOL", "fifa_rank": 40, "rating": 1505.35, "pot": 3},
    {"name": "Scotland", "code": "SCO", "confederation": "UEFA", "fifa_rank": 42, "rating": 1503.34, "pot": 3},
    {"name": "DR Congo", "code": "COD", "confederation": "CAF", "fifa_rank": 45, "rating": 1477.06, "pot": 4},
    {"name": "Tunisia", "code": "TUN", "confederation": "CAF", "fifa_rank": 46, "rating": 1476.40, "pot": 3},
    {"name": "Uzbekistan", "code": "UZB", "confederation": "AFC", "fifa_rank": 50, "rating": 1458.73, "pot": 3},
    {"name": "Qatar", "code": "QAT", "confederation": "AFC", "fifa_rank": 54, "rating": 1450.00, "pot": 3},
    {"name": "Iraq", "code": "IRQ", "confederation": "AFC", "fifa_rank": 57, "rating": 1446.28, "pot": 4},
    {"name": "Saudi Arabia", "code": "KSA", "confederation": "AFC", "fifa_rank": 60, "rating": 1423.88, "pot": 3},
    {"name": "South Africa", "code": "RSA", "confederation": "CAF", "fifa_rank": 61, "rating": 1414.88, "pot": 3},
    {"name": "Bosnia", "code": "BIH", "confederation": "UEFA", "fifa_rank": 63, "rating": 1395.20, "pot": 4},
    {"name": "Jordan", "code": "JOR", "confederation": "AFC", "fifa_rank": 64, "rating": 1387.74, "pot": 4},
    {"name": "Cabo Verde", "code": "CPV", "confederation": "CAF", "fifa_rank": 67, "rating": 1371.11, "pot": 4},
    {"name": "Ghana", "code": "GHA", "confederation": "CAF", "fifa_rank": 73, "rating": 1346.88, "pot": 4},
    {"name": "Curacao", "code": "CUR", "confederation": "CONCACAF", "fifa_rank": 82, "rating": 1287.00, "pot": 4},
    {"name": "Haiti", "code": "HAI", "confederation": "CONCACAF", "fifa_rank": 84, "rating": 1277.67, "pot": 4},
    {"name": "New Zealand", "code": "NZL", "confederation": "OFC", "fifa_rank": 85, "rating": 1275.58, "pot": 4},
]

REAL_GROUPS = {
    "A": ["Mexico", "South Africa", "South Korea", "Czechia"],
    "B": ["Canada", "Bosnia", "Qatar", "Switzerland"],
    "C": ["Brazil", "Morocco", "Haiti", "Scotland"],
    "D": ["USA", "Paraguay", "Australia", "Turkey"],
    "E": ["Germany", "Curacao", "Ivory Coast", "Ecuador"],
    "F": ["Netherlands", "Japan", "Sweden", "Tunisia"],
    "G": ["Belgium", "Egypt", "Iran", "New Zealand"],
    "H": ["Spain", "Cabo Verde", "Saudi Arabia", "Uruguay"],
    "I": ["France", "Senegal", "Iraq", "Norway"],
    "J": ["Argentina", "Algeria", "Austria", "Jordan"],
    "K": ["Portugal", "DR Congo", "Uzbekistan", "Colombia"],
    "L": ["England", "Croatia", "Ghana", "Panama"],
}

FLAGS = {
    "Spain": "🇪🇸",
    "France": "🇫🇷",
    "England": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Portugal": "🇵🇹",
    "Netherlands": "🇳🇱",
    "Belgium": "🇧🇪",
    "Germany": "🇩🇪",
    "Croatia": "🇭🇷",
    "Switzerland": "🇨🇭",
    "Austria": "🇦🇹",
    "Turkey": "🇹🇷",
    "Norway": "🇳🇴",
    "Sweden": "🇸🇪",
    "Czechia": "🇨🇿",
    "Scotland": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Bosnia": "🇧🇦",
    "Argentina": "🇦🇷",
    "Brazil": "🇧🇷",
    "Colombia": "🇨🇴",
    "Uruguay": "🇺🇾",
    "Ecuador": "🇪🇨",
    "Paraguay": "🇵🇾",
    "USA": "🇺🇸",
    "Mexico": "🇲🇽",
    "Canada": "🇨🇦",
    "Panama": "🇵🇦",
    "Curacao": "🇨🇼",
    "Haiti": "🇭🇹",
    "Morocco": "🇲🇦",
    "Senegal": "🇸🇳",
    "Egypt": "🇪🇬",
    "Ivory Coast": "🇨🇮",
    "Algeria": "🇩🇿",
    "Tunisia": "🇹🇳",
    "Ghana": "🇬🇭",
    "South Africa": "🇿🇦",
    "DR Congo": "🇨🇩",
    "Cabo Verde": "🇨🇻",
    "Japan": "🇯🇵",
    "Iran": "🇮🇷",
    "South Korea": "🇰🇷",
    "Australia": "🇦🇺",
    "Saudi Arabia": "🇸🇦",
    "Qatar": "🇶🇦",
    "Iraq": "🇮🇶",
    "Uzbekistan": "🇺🇿",
    "Jordan": "🇯🇴",
    "New Zealand": "🇳🇿",
}

GROUP_LETTERS = list("ABCDEFGHIJKL")
